quiz/urls.py
from django.urls import path
from . import views
app_name='quiz1'

urlpatterns=[
    path('',views.Login.as_view(),name='login'),
    path('register',views.Register.as_view(),name='register'),
    path('index',views.index.as_view(),name='index'),
    path('logout',views.Logout.as_view(),name='logout'),
    path('quiz_form',views.Quizcreate.as_view(),name='quiz_form'),
    path('quizcreate',views.Quizcontent.as_view(),name='quizcontent'),
    path('play/<int:yo>/',views.Play.as_view(),name='play'),
    path('quizscore/<int:yo>',views.Quizrank.as_view(),name='quizscore'),
]

quiz1/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quiz.urls')),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
class Quiz(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quiz_name=models.CharField(max_length=400)
    no_q=models.IntegerField(default=0)
    genre=models.CharField(max_length=400)
    count=models.IntegerField(default=1)
    array=models.IntegerField(default=0)
class Question(models.Model):
    quiz=models.ForeignKey(Quiz,on_delete=models.CASCADE)
    question=models.CharField(max_length=800)



class Answer(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    answer = models.CharField(max_length=800)
class Player(models.Model):
    quiz=models.ForeignKey(Quiz,on_delete=models.CASCADE)
    score=models.IntegerField(default=0)
    name=models.CharField(max_length=400)

quiz/forms.py
from django import forms
from django.contrib.auth.models import User
class User_form(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','email','password']

quiz/views.py
from django.shortcuts import render,redirect
from django.shortcuts import HttpResponse
from .models import Quiz,Question,Answer,Player
from .forms import User_form
from django.views import generic
from django.views.generic import View
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import  login_required
from django.utils.decorators import method_decorator
from datetime import datetime

# Create your views here.
#Index Pageclass index(View):

class index(View):
    #@method_decorator(login_required(login_url='quiz1:login'))

    def get(self,request):
        quiz = Quiz.objects.filter(user=request.user)
        return render(request, 'quiz/index.html', {'all_quiz': quiz})





#Registeration Page
class Register(View):
    form_name=User_form
    def get(self,request):
        form=self.form_name(None)
        return render(request,'quiz/register.html',{'form':form})
    def post(self,request):
        form=self.form_name(request.POST)
        if form.is_valid():
            user=form.save(commit=False)
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']
            email=form.cleaned_data['email']
            user.set_password(password)
            user.save()
            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('quiz1:index')
        return render(request,'quiz/register.html',{'form':form})
#Login Page
class Login(View):
    def get(self,request):
        return render(request,'quiz/login.html')
    def post(self,request):
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(request,username=username,password=password)
        if user:
            login(request,user)
            request.session['name']=request.POST['username']
            return redirect('quiz1:index')

        return render(request,'quiz/login.html',{'error':'Username or password is incorrect'})
#Logout Page
class Logout(View):
    def get(self,request):
        logout(request)
        return redirect('quiz1:login')
#Quiz creating

class Quizcreate(View):


    def get(self,request):
        return render(request,'quiz/quiz_form.html')
    def post(self,request):
        quiz_name=request.POST['quiz_name']
        genre=request.POST['genre']
        no_q=request.POST['no_q']
        quiz=Quiz(user=request.user,quiz_name=quiz_name,no_q=no_q,genre=genre)
        quiz.save()
        return redirect('quiz1:quizcontent')
class Quizcontent(View):

    def get(self,request):
        quiz = Quiz.objects.order_by('-pk')[0]
        return render(request,'quiz/quizcontent.html',{'num':'1','quiz':quiz})
    def post(self,request):


        quiz=Quiz.objects.order_by('-pk')[0]
        question=request.POST['question']
        answer = request.POST['answer']
        numb=quiz.no_q
        quiz.count=quiz.count+1
        quiz.save()
        q=Question(quiz=quiz,question=question)
        q.save()
        a=Answer(quiz=quiz,answer=answer)
        a.save()
        if quiz.count <= numb:
            return render(request,'quiz/quizcontent.html',{'num':quiz.count})
        else:
            return redirect('quiz1:index')
class Play(View):
    def get(self,request,*args,**kwargs):
        name=request.user.username
        quiz=Quiz.objects.get(pk=self.kwargs['yo'])
        quiz.count = 1
        quiz.array = 0
        quiz.save()
        x = Player(quiz=quiz, name=name)
        x.save()
        que = Question.objects.filter(quiz=quiz).order_by('pk')[quiz.array]


        return render(request,'quiz/play.html',{'que':que,'quiz':quiz,'no':quiz.count})


    def post(self,request,*args,**kwargs):

        name = request.user.username
        quiz = Quiz.objects.get(pk=self.kwargs['yo'])
        ans=Answer.objects.filter(quiz=quiz).order_by('pk')[quiz.array]
        answer=request.POST['answer']
        que = Question.objects.filter(quiz=quiz).order_by('pk')[quiz.array]
        x=Player.objects.order_by('-pk')[0]
        if answer!=ans.answer:
            error='Sorry! Answer is not correct!'
            return render(request, 'quiz/play.html', {'que': que, 'quiz': quiz, 'no': quiz.count,'error':error})
        else:
            x.score=x.score+1
            x.save()
            quiz.array=quiz.array+1
            quiz.count=quiz.count+1
            quiz.save()
            if quiz.count<=quiz.no_q:
                que = Question.objects.filter(quiz=quiz).order_by('pk')[quiz.array]
                return render(request, 'quiz/play.html', {'que': que, 'quiz': quiz, 'no': quiz.count})
            else:
                quiz.array=0
                quiz.count=1
                quiz.save()
                return redirect('quiz1:index')
class Quizrank(View):
    def get(self,request,*args,**kwargs):
        quiz=Quiz.objects.get(pk=self.kwargs['yo'])
        player=Player.objects.filter(quiz=quiz).order_by('-score')
        return render(request,'quiz/quizscore.html',{'player':player,'quiz':quiz})

quiz/templates/quiz/base.html
<!DOCTYPE html>
<html lang="en">
<head>

  {%load staticfiles%}
    <title>{%block title%}{%endblock%}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'quiz/style.css' %}" />

<link href="https://fonts.googleapis.com/css?family=Bungee&display=swap" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Bungee+Shade&display=swap" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Seymour+One&display=swap" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Black+Ops+One|Seymour+One&display=swap" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Archivo+Black&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Monoton&display=swap" rel="stylesheet">
<style>
  {%block style%}
  {%endblock%}
</style>

</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background:
	 none;">
  <a class="navbar-brand" style="color:   #e6e6e6;



    font-family: 'Black Ops One', cursive;



font-size:40px;

"href="#">QuiziFied</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"  aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span style="color: #d9d9d9;



    font-family: 'Bungee', cursive;


">Menu</span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" style="font-size:25px;color:#d9d9d9;

    font-family: 'Bungee', cursive;


"href="{%url 'quiz1:logout'%}">Logout <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" style="font-size:25px;color:#d9d9d9;
   font-family: 'Bungee', cursive;

"href="#">Quiz create<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" style="font-size:25px;color:#d9d9d9;
    font-family: 'Bungee', cursive;

"href="#">Your scores<span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit" style="

    font-family: 'Lobster', cursive;

">Search</button>
    </form>
  </div>
</nav>
{%block content%}
{%endblock%}
</body>
</html>

quiz/templates/quiz/index.html
{%extends 'quiz/base.html'%}
{%block title%}Index{%endblock%}
{%block style%}


/* DEMO-SPECIFIC STYLES */
.typewriter h1 {
  color: #fff;
  font-family: monospace;
  overflow: hidden; /* Ensures the content is not revealed until the animation */
  border-right: .15em solid orange; /* The typwriter cursor */
  white-space: nowrap; /* Keeps the content on a single line */
  margin: 0 auto; /* Gives that scrolling effect as the typing happens */
  letter-spacing: .15em; /* Adjust as needed */
  animation:
    typing 3.5s steps(30, end),
    blink-caret .5s step-end infinite;
}

/* The typing effect */
@keyframes typing {
  from { width: 0 }
  to { width: 100% }
}

/* The typewriter cursor effect */
@keyframes blink-caret {
  from, to { border-color: transparent }
  50% { border-color: blue; }
}


.ribbon {
 font-size: 16px !important;
 /* This ribbon is based on a 16px font side and a 24px vertical rhythm. I've used em's to position each element for scalability. If you want to use a different font size you may have to play with the position of the ribbon elements */

 width: 50%;


 position: relative;
 background:  	#6699cc;
 color: #fff;
 text-align: center;
 padding: 1em 2em; /* Adjust to suit */
 margin: 2em auto 3em; /* Based on 24px vertical rhythm. 48px bottom margin - normally 24 but the ribbon 'graphics' take up 24px themselves so we double it. */
}
.ribbon:before, .ribbon:after {
 content: "";
 position: absolute;
 display: block;
 bottom: -1em;
 border: 1.5em solid #6666cc;
 z-index: -1;

}
.ribbon:before {
 left: -2em;
 border-right-width: 1.5em;
 border-left-color: transparent;
}
.ribbon:after {
 right: -2em;
 border-left-width: 1.5em;
 border-right-color: transparent;
}
.ribbon .ribbon-content:before, .ribbon .ribbon-content:after {
 content: "";

 position: absolute;
 display: block;
 border-style: solid;
 border-color: #667fcc transparent transparent transparent;
 bottom: -1em;
}
.ribbon .ribbon-content:before {
 left: 0;
 border-width: 1em 0 0 1em;
}
.ribbon .ribbon-content:after {
 right: 0;
 border-width: 1em 1em 0 0;
}

@media only screen and (max-width:600px){
button{
margin-left:150px;
}
.ribbon{
font-size:30px;
}


{%endblock%}
{%block content%}
<br>
<br>
<br>
<br>
<div class="container-fluid">
    <div class="row">
<div class="col-sm-2" ></div>
        <div class="col-sm-8">
<div class="typewriter" >
  <a href="{%url 'quiz1:quiz_form'%}"><h1 style="

    font-family: 'Bungee', cursive;

">Click here to make your quiz trivia.</h1></a>
</div>

<br>
<div class="container-fluid">
<h1 class="ribbon shadow-lg p-3 mb-5 rounded" style="width:60%;text-shadow:3px 3px  4px blue;">
    <strong class="ribbon-content"><h1 style="



    font-family: 'Bungee', cursive;



">Welcome {{request.session.name}}
    <br>Language is {{language}}</h1></strong>
</h1></div>

<h1>{{request.user.username}}</h1>
            </div>
<div class="col-sm-2" ></div>
        </div>
</div>

<div class="container-fluid" style="margin-top:50px;">
  <div class="row">
    <div class="col-sm-1" ></div>
      <div class="col-sm-10" style="height:500px;padding:10px;border-radius:10px;">
{%for quiz in all_quiz%}<br>
          <div class="row" style="background:none;">

              <br>
              <div style="background:white;width:100%;height:10px;border-radius:10px;"></div>
              <div class="col-sm-1" style="text-align:center;color:black;"><h2 style="

    font-family: 'Bungee', cursive;margin-top:20px;color:white;

">{{forloop.counter}}</h2></div>
              <div class="col-sm-4" style="text-align:center;color:red;margin-top:20px;"><h2 style="

    font-family: 'Bungee', cursive;

">{{quiz.quiz_name}}</h2></div>


              <div class="col-sm-3" style="text-align:center;"><h3 style="color:white;margin-top:20px;

    font-family: 'Bungee', cursive;

">{{quiz.genre}}</h3></div>


              <div class="col-sm-1" style="text-align:center;"><h3
   style=" font-family: 'Bungee', cursive;margin-top:20px;color:red;">{{quiz.no_q}}</h3></div>
              <div class="col-sm-1">
                  <button type="submit" style="border-radius:20px;height:40px;width:120px;color:white;background:red;margin-top:20px;"><a href="{%url 'quiz1:play' quiz.id%}" style="color:white;">Play Quiz</a></button>

              </div>
              <div class="col-sm-2">
                  <button type="submit" style="border-radius:20px;height:40px;width:120px;color:white;background:white;margin-top:20px;"><a href="{%url 'quiz1:quizscore' quiz.id%}" stycolor"">Quiz Score</a></button>
<br><br>
              </div>


          </div>
          {%endfor%}









<button type="button"><a href="{%url 'quiz1:logout'%}">LOgout</a> </button>
<button type="button"><a href="{%url 'quiz1:quiz_form'%}">Quiz Create</a></button>
</div>

    <div class="col-sm-1" ></div>
  </div>
    <footer>
        <div class="container-fluid" style="background:black;height:100px;margin-top:80px;width:100%;opacity:0.7;">
            <i class="fa fa-facebook-official w3-hover-opacity"></i>
    <i class="fa fa-instagram w3-hover-opacity"></i>
    <i class="fa fa-snapchat w3-hover-opacity"></i>
    <i class="fa fa-pinterest-p w3-hover-opacity"></i>
    <i class="fa fa-twitter w3-hover-opacity"></i>
    <i class="fa fa-linkedin w3-hover-opacity"></i>
        </div>
    </footer>
{%endblock%}

quiz/templates/quiz/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOgin</title>
</head>
<body>
<form method="post">
    {%csrf_token%}
    <label for="yo">Username</label>
    <input type="text" id="yo" name="username" required/>

     <label for="yo2">Password</label>
    <input type="password" id="yo2" name="password" required/>
    <input type="submit" value="submit">
    <button type="button"><a href="{%url 'quiz1:register'%}">Register</a></button>
    {%if error%}
    {{error}}
    {%endif%}
</form>
</body>
</html>

quiz/templates/quiz/play.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Play QUiz</title>
</head>
<body>
<button type="submit"><a href="{%url 'quiz1:quizscore' quiz.id%}">Quiz Score</a></button>

<h1>{{request.user}}</h1>
<h2>{{quiz.quiz_name}}</h2><br>
<h2>Q.{{no}}</h2>
<h3>Question:{{que.question}}</h3>
<form method="post">
    {%csrf_token%}
    <label for="yo">Answer:</label>
    <input type="text" id="yo" name="answer" required/>
    <input type="submit" value="Submit">
</form>
{%if error%}
{{error}}
{%endif%}
{{ans}}
<button type="button"><a href="{%url 'quiz1:index'%}">End Quiz</a> </button>
</body>
</html>

quiz/templates/quiz/quiz_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>quiz Form</title>
</head>
<body>
<form method="post">
    {%csrf_token%}
  <label for="yo">Quiz Name</label>
    <input type="text" id="yo" name="quiz_name" required/>
     <label for="yo1">Number of Questions</label>
    <input type="number" id="yo1"name="no_q" required/>
     <label for="yo2">Genre</label>
    <input type="text" id="yo2" name="genre" required/>
    <input type="submit" value="submit">
</form>
</body>
</html>

quiz/templates/quiz/quizcontent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quiz COntent</title>
</head>
<body>
<h1>{{quiz.quiz_name}}</h1><br>
<h3>Q.{{num}}</h3><br>
<form method="post">
    {%csrf_token%}
    <label id="yo">Question:</label>
    <input id="yo" type="text" name="question">
    <label id="yo1">Answer:</label>
    <input id="yo1" type="text" name="answer">
    <input type="submit" value="submit">
</form>
</body>
</html>

quiz/templates/quiz/quizscore.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Quiz score</title>
</head>
<body>
<h2>{{quiz.quiz_name}}</h2><br>
<table>
    <tr>
        <th>Player Name</th>
        <th>Score</th>
    </tr>
    {%for play in player%}
    <tr>
        <td>{{play.name}}</td>
        <td>{{play.score}}</td>
    </tr>
    {%endfor%}

</table><br>
<button type="button"><a href="{%url 'quiz1:index'%}">Get Back to Menu</a></button>
</body>
</html>

quiz/templates/quiz/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
<form method="post">
    {%csrf_token%}
    <label for="yo">Username</label>
    <input type="text" id="yo" name="username" required/>
     <label for="yo1">Email</label>
    <input type="text" id="yo1"name="email" required/>
     <label for="yo2">Password</label>
    <input type="password" id="yo2" name="password" required/>
    <input type="submit" value="submit">
    {% if form.errors%}
    {{form.errors}}
    {%endif%}
</form>
</body>
</html>